### ISSUE TITLE
Improve installer: ensure all files from previous installations have been uninstalled

### ISSUE THREAD

**Issue by moonyrox** [lallulli/songpress#36] opened 2019-02-14 03:27 UTC
just downloaded current update and now the program doesn't load at all!

**Comment by lallulli** [comment] 2019-02-14 07:18
I'm sorry to hear that. Could you please give more information about the problem: do you get any error message? How do you start Songpress (from Windows start menu, double-clicking a file, etc.?) Which operating system do you use?

There is a known issue in last version, where you cannot open a file by double-clicking it (or using command line). It has been fixed in commit ff6ab0a

**Comment by moonyrox** [comment] 2019-02-15 06:51
Hi, thanks for getting back to me.
I went to open Songpress yesterday and was informed of a new update, which
i installed. This removed the old version and installed the new version.
I've since tried to update another half dozen times or so with the same
result- whether by double-clicking the icon on the desktop or from the
Windows start menu. I've attached a photo of the message that comes up. I
am using the current version of windows.

Really hope this can be fixed as i really like the program and have come to
rely on it heavily- would happily pay for a working version of it!

Look forward to hearing from you,

Dave

Edit: my reply is too large to send with the photo of the error message
apparently.

It's quite a large message but the first line reads:  "cx..Freeze: Python
error in main script"

It then goes on with a whole heap of text that might as well be another
language to me!

**Comment by lallulli** [comment] 2019-02-15 07:23
Hi Dave,

thank you for your feedback. I would really need that message, otherwise
I'm not able to understand what's going on in your case.

You should be able to copy the whole text of the message window, and paste
it in your reply. Just click on the text, press CTRL-A (select all) and
CTRL-C (copy).

I'm looking forward to hearing from you again.


Il giorno ven 15 feb 2019, 07:51 moonyrox <notifications@github.com> ha
scritto:

> Hi, thanks for getting back to me.
> I went to open Songpress yesterday and was informed of a new update, which
> i installed. This removed the old version and installed the new version.
> I've since tried to update another half dozen times or so with the same
> result- whether by double-clicking the icon on the desktop or from the
> Windows start menu. I've attached a photo of the message that comes up. I
> am using the current version of windows.
>
> Really hope this can be fixed as i really like the program and have come to
> rely on it heavily- would happily pay for a working version of it!
>
> Look forward to hearing from you,
>
> Dave
>
> Edit: my reply is too large to send with the photo of the error message
> apparently.
>
> It's quite a large message but the first line reads: "cx..Freeze: Python
> error in main script"
>
> It then goes on with a whole heap of text that might as well be another
> language to me!
>

**Comment by moonyrox** [comment] 2019-02-15 07:51
No it won’t let me copy the text- can’t click on the text, can’t right-click, or copy/paste. I can either send a photo (which is too large apparently) or I could try to type it all down I guess

**Comment by lallulli** [comment] 2019-02-15 08:06
I understand. You can use a program that comes with Windows, named "Snipping tool", that allows you to take a screenshot. It is much smaller than a photo. If you have problems in attaching the snapshot, reply on GitHub (https://github.com/lallulli/songpress/issues/36) rather than by email.
Thank you!

**Comment by moonyrox** [comment] 2019-02-19 22:32
Hi!
Any progress with this?

Regards 
Dave

**Comment by lallulli** [comment] 2019-02-20 18:10
Hi Dave. Yesterday I released Songpress 1.7.2, which fixes a bug --
apparently, not the bug you are referring to. Please try the new version,
and let me know if it works for you. If it doesn't, I really need your
feedback in order to fix your problem: it is essential for me to read the
exact error message you encounter. Thanks!

Il giorno mar 19 feb 2019 alle ore 23:32 moonyrox <notifications@github.com>
ha scritto:

> Hi!
> Any progress with this?
>
> Regards
> Dave
>
> Sent from my iPhone
>

**Comment by moonyrox** [comment] 2019-02-20 18:51
Ok- I’ll give it a try when I get home. I did send through a screw of the error I was getting, did you receive that?

Regards

**Comment by lallulli** [comment] 2019-02-21 18:42
Sorry, no, I didn't receive the error message. You can check the history of this conversation on Github: https://github.com/lallulli/songpress/issues/36

Alternatively, you could send me an email at luca@skeed.it

**Comment by lallulli** [comment] 2019-02-21 19:14
Thank you for your screenshot, I'm attaching it here for future reference.
![image](https://user-images.githubusercontent.com/548413/53195103-38ff9d80-3615-11e9-967d-d4559f3d6b13.png)

**Comment by lallulli** [comment] 2019-02-21 21:04
Dave, may have you installed Songpress 1.7 without uninstalling Songpress 1.6?

You can try to completely wipe off the installation directory of Songpress, which can be either `C:\Program Files (x86)\Songpress` or `C:\Program Files\Songpress`, and then perform a clean install. Please let me know if it works.

**Comment by moonyrox** [comment] 2019-02-22 06:08
When i installed Songpress 1.7 part of the process was the uninstalling of
version 1.6 which i did do.

I've just uninstalled 1.7 and installed 1.7.2

Sadly i'm still getting the error message.

Perhaps i'm just not going to be able to use this program anymore, which is
a real shame!

**Comment by lallulli** [comment] 2019-02-22 19:23
The error message you are getting *may* be caused by a conflict between different versions of a "library" file (maybe a file called `_socket.pyd`) in the installation directory of Songpress - due to a leftover from a previous version that, for some reason, has not been completely unistalled. This is the reason why I asked you to delete manually the whole installation directory of Songpress, and reinstall it from scratch.

Another thing you could try is to uninstall and install Songpress again, specifying a different installation directory.

**Comment by moonyrox** [comment] 2019-02-23 07:06
Hi!

Success! I found and deleted the version that was in C:\Program Files (x86) and
then re-installed in the C:\Program Files\ directory.

This seems to have worked- well, no error message and the program opens
now! Thank you very much for taking the time to help a dummy like me, it's
very much appreciated. I'll be sure to make a donation to support your
program.

Thanks again

Dave

**Comment by lallulli** [comment] 2019-02-23 07:51
Hi Dave, I'm glad it worked! :-D

You're very welcome. It's not your fault. Apparently the installer is not robust enough to handle all situations properly. It's important for me to be aware of the problem and its cause, so that I can improve it. Thanks again for your report, and have fun with Songpress.

**Comment by moonyrox** [comment] 2019-02-23 22:00
I’m currently formatting a heap of songs for use in Onsong. Songpress makes it so easy and having them in a chordpro file is sooo much better than just a word or text file.
Thanks again for a great program- glad I could help out (if that’s what it was haha!)

Regards 
Dave

**Closed** 2021-04-05 07:49 UTC
